version: '3'

services:
   app:
     build:
       context: .
       dockerfile: Dockerfile
       args:
         DJANGO_ENV: dev
     image: blog
     container_name: blog-app
     env_file:
       - .env
     command: "bash ./runserver.sh"
     volumes:
       - .:/app
     expose:
       - "8000"
     ports:
       - "8000:8000"
     depends_on:
       - db
   db:
     image: postgres:11
     container_name: postgres
     restart: always
     env_file:
       - .env
     volumes:
       - db-data:/var/lib/postgresql/data
     expose:
       - "5432"

volumes:
  db-data:
    driver: local